/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2021-09-28 00:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jspEx;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MemberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("\tfunction fn_sendMember(){\r\n");
      out.write("\t\t//alert(\"fn_sendMember()\");\r\n");
      out.write(" \t\tvar frmMember = document.frmMember;\r\n");
      out.write(" \t\tvar id = frmMember.id.value.trim();\r\n");
      out.write("\t\tvar pwd = frmMember.pwd.value.trim();\r\n");
      out.write("\t\tvar name = frmMember.name.value.trim();\r\n");
      out.write("\t\tvar email = frmMember.email.value.trim();\r\n");
      out.write("\t\tvar post = frmMember.post.value.trim();\r\n");
      out.write("\t//\tdocument.getElementById(\"name\").value = 'val';\r\n");
      out.write("\t\tif(id.length == 0 || id == '')\r\n");
      out.write("\t\t\talert(\"아이디는 필수입니다.\");\r\n");
      out.write("\t\telse if(pwd.length == 0 || pwd == '')\r\n");
      out.write("\t\t\talert(\"비밀번호는 필수입니다.\");\r\n");
      out.write("\t\telse if(name.length == 0 || name == '')\r\n");
      out.write("\t\t\talert(\"이름은 필수입니다.\");\r\n");
      out.write("\t\telse if(email.length == 0 || email == '')\r\n");
      out.write("\t\t\talert(\"이메일은 필수입니다.\");\r\n");
      out.write("\t\telse if(post.length == 0 || post == '')\r\n");
      out.write("\t\t\talert(\"우편번호는 필수입니다.\");\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tfrmMember.method = \"post\";\r\n");
      out.write("\t\t\tfrmMember.action = \"UserInfoAddServlet\";\r\n");
      out.write("\t\t\tfrmMember.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write(" \t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction idCheck(){\r\n");
      out.write(" \t\t//var frmMember = document.frmMember;\r\n");
      out.write("\t\tvar id = frmMember.id.value;\r\n");
      out.write("\t\tif(id.length == 0 || id == '')\r\n");
      out.write("\t\t\talert(\"아이디는 필수입니다.\");\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t//팝업창\r\n");
      out.write("\t\t\twindow.open('CheckIdServlet?id='+id, 'pop', 'width=300,height=300');//세번째 인자값 하나로 묶을 것\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchPost(){\r\n");
      out.write("\t\tvar post = frmMember.post.value;\r\n");
      out.write("\t\twindow.open('jspEx/Post.jsp', 'pop', 'width=500,height=500');//세번째 인자값 하나로 묶을 것\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchPost(){\r\n");
      out.write("\t\tvar dong = frmMember.post.value.trim();\r\n");
      out.write("\t\tconsole.log(dong.length+'->'+dong);\r\n");
      out.write("\t\tif(dong.length == null || dong == '')\r\n");
      out.write("\t\t\talert(\"~동을 입력해주세요\");\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\twindow.open('/webapp/PostServlet?dong='+dong,'pop','width=600,height=500');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <form name = \"frmMember\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<th> 회원 가입창</th>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"id\">\r\n");
      out.write("<!-- \t\t\t\t<input type = \"button\" value = \"아이디 중복체크\" onclick = \"location.href = '/webapp/jspEx/CheckId.jsp?id =12'\">\r\n");
      out.write("-->\t\t\t<input type = \"button\" value = \"아이디 중복체크\" onclick = \"idCheck()\"></td>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t<td><input type = \"password\" name = \"pwd\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"email\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<!-- 추가 -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>우편번호</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"post\">\r\n");
      out.write("\t\t\t<input type = \"button\" value = \"우편번호 검색\", onclick = \"searchPost()\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type = \"button\" value = \"가입하기\" onclick = \"fn_sendMember()\">\r\n");
      out.write("\t<input type = \"reset\" value = \"다시입력\">\r\n");
      out.write("\t<input type = \"hidden\" name = \"command\" value = \"addMember\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
